"""Seed data for the 20-song demo database.

Two kinds of entries:
  - Public-domain classical: composition is public domain, free CC/PD recordings
    exist (Musopen / IMSLP), so `preview_url` can point at a real playable clip.
  - Modern copyrighted songs: metadata only, searchable by text, but
    `preview_url` is None because hosting the recording would infringe copyright.

`melody_contour` is a placeholder for phase 2 (query-by-humming). Leave [] for now.
"""

SONGS = [
    # ---------- Public-domain classical (real audio possible) ----------
    {
        "id": 1,
        "title": "Eine kleine Nachtmusik (1st mvt)",
        "artist": "Wolfgang Amadeus Mozart",
        "year": 1787,
        "genre": ["classical", "serenade"],
        "lyric_snippet": "",
        "mood_keywords": ["elegant", "bright", "cheerful", "courtly", "playful"],
        "description": "Lively, instantly recognizable string serenade with a bouncy, optimistic main theme.",
        "preview_url": "PD_AUDIO",  # replace with hosted Musopen/IMSLP clip
        "melody_contour": [],
    },
    {
        "id": 2,
        "title": "Symphony No. 5 (1st mvt)",
        "artist": "Ludwig van Beethoven",
        "year": 1808,
        "genre": ["classical", "symphony"],
        "lyric_snippet": "",
        "mood_keywords": ["dramatic", "dark", "powerful", "fate", "intense"],
        "description": "Famous four-note 'da-da-da-dum' opening; stormy, driving, dramatic orchestral piece.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 3,
        "title": "Clair de Lune",
        "artist": "Claude Debussy",
        "year": 1905,
        "genre": ["classical", "impressionist", "piano"],
        "lyric_snippet": "",
        "mood_keywords": ["dreamy", "calm", "gentle", "moonlight", "soft", "romantic"],
        "description": "Soft, flowing solo piano piece evoking moonlight; calm and introspective.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 4,
        "title": "Spring (Four Seasons)",
        "artist": "Antonio Vivaldi",
        "year": 1725,
        "genre": ["classical", "baroque", "concerto"],
        "lyric_snippet": "",
        "mood_keywords": ["bright", "joyful", "energetic", "spring", "birdsong"],
        "description": "Cheerful baroque violin concerto imitating birdsong and the arrival of spring.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 5,
        "title": "Canon in D",
        "artist": "Johann Pachelbel",
        "year": 1680,
        "genre": ["classical", "baroque"],
        "lyric_snippet": "",
        "mood_keywords": ["serene", "uplifting", "wedding", "peaceful", "graceful"],
        "description": "Gently building, repeating chord progression; a calm, hopeful piece common at weddings.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 6,
        "title": "Ride of the Valkyries",
        "artist": "Richard Wagner",
        "year": 1856,
        "genre": ["classical", "opera", "orchestral"],
        "lyric_snippet": "",
        "mood_keywords": ["epic", "powerful", "heroic", "intense", "soaring"],
        "description": "Thunderous, soaring brass theme; grand and aggressive orchestral spectacle.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 7,
        "title": "Symphony No. 9 'Ode to Joy'",
        "artist": "Ludwig van Beethoven",
        "year": 1824,
        "genre": ["classical", "symphony", "choral"],
        "lyric_snippet": "Freude, schoner Gotterfunken",
        "mood_keywords": ["joyful", "triumphant", "uplifting", "hopeful", "grand"],
        "description": "Triumphant, soaring choral melody celebrating joy and human brotherhood.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 8,
        "title": "Hungarian Dance No. 5",
        "artist": "Johannes Brahms",
        "year": 1869,
        "genre": ["classical", "dance"],
        "lyric_snippet": "",
        "mood_keywords": ["fiery", "playful", "energetic", "dramatic", "folk"],
        "description": "Fast, fiery folk-flavored dance with sudden tempo changes; playful and dramatic.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 9,
        "title": "The Blue Danube",
        "artist": "Johann Strauss II",
        "year": 1866,
        "genre": ["classical", "waltz"],
        "lyric_snippet": "",
        "mood_keywords": ["graceful", "flowing", "elegant", "waltz", "sweeping"],
        "description": "Sweeping, elegant waltz with a lilting, instantly hummable main theme.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },
    {
        "id": 10,
        "title": "Gymnopedie No. 1",
        "artist": "Erik Satie",
        "year": 1888,
        "genre": ["classical", "piano", "minimalist"],
        "lyric_snippet": "",
        "mood_keywords": ["melancholy", "slow", "calm", "wistful", "spacious"],
        "description": "Slow, sparse, melancholic solo piano; quietly reflective and bittersweet.",
        "preview_url": "PD_AUDIO",
        "melody_contour": [],
    },

    # ---------- Modern, copyrighted (metadata only, no audio) ----------
    {
        "id": 11,
        "title": "Billie Jean",
        "artist": "Michael Jackson",
        "year": 1982,
        "genre": ["pop", "funk", "dance"],
        "lyric_snippet": "Billie Jean is not my lover",
        "mood_keywords": ["groovy", "danceable", "tense", "iconic", "bassline"],
        "description": "Funky, driving bassline-led pop song with a tense, danceable groove.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 12,
        "title": "Bohemian Rhapsody",
        "artist": "Queen",
        "year": 1975,
        "genre": ["rock", "progressive"],
        "lyric_snippet": "Is this the real life? Is this just fantasy?",
        "mood_keywords": ["epic", "operatic", "dramatic", "theatrical", "shifting"],
        "description": "Multi-part epic shifting between ballad, opera, and hard rock.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 13,
        "title": "Smells Like Teen Spirit",
        "artist": "Nirvana",
        "year": 1991,
        "genre": ["rock", "grunge", "alternative"],
        "lyric_snippet": "Here we are now, entertain us",
        "mood_keywords": ["angsty", "loud", "raw", "rebellious", "distorted"],
        "description": "Raw, distorted grunge anthem alternating quiet verses and explosive choruses.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 14,
        "title": "Rolling in the Deep",
        "artist": "Adele",
        "year": 2010,
        "genre": ["pop", "soul"],
        "lyric_snippet": "We could have had it all",
        "mood_keywords": ["powerful", "soulful", "heartbreak", "building", "intense"],
        "description": "Soulful, building breakup anthem with a huge, emotional chorus.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 15,
        "title": "HUMBLE.",
        "artist": "Kendrick Lamar",
        "year": 2017,
        "genre": ["rap", "hip-hop"],
        "lyric_snippet": "Sit down, be humble",
        "mood_keywords": ["hard", "minimal", "confident", "punchy", "modern"],
        "description": "Hard-hitting modern rap with a minimal piano loop and punchy delivery.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 16,
        "title": "Take Five",
        "artist": "The Dave Brubeck Quartet",
        "year": 1959,
        "genre": ["jazz"],
        "lyric_snippet": "",
        "mood_keywords": ["cool", "smooth", "swinging", "laid-back", "5/4"],
        "description": "Cool, smooth jazz standard in an unusual 5/4 time with a relaxed sax theme.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 17,
        "title": "Midnight City",
        "artist": "M83",
        "year": 2011,
        "genre": ["electronic", "synth-pop"],
        "lyric_snippet": "",
        "mood_keywords": ["dreamy", "nostalgic", "anthemic", "synthy", "soaring"],
        "description": "Dreamy, nostalgic synth-pop anthem with a soaring saxophone outro.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 18,
        "title": "Get Lucky",
        "artist": "Daft Punk",
        "year": 2013,
        "genre": ["electronic", "disco", "funk"],
        "lyric_snippet": "We're up all night to get lucky",
        "mood_keywords": ["funky", "upbeat", "groovy", "feel-good", "disco"],
        "description": "Feel-good disco-funk groove with a catchy, repeating hook.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 19,
        "title": "Shape of You",
        "artist": "Ed Sheeran",
        "year": 2017,
        "genre": ["pop"],
        "lyric_snippet": "I'm in love with the shape of you",
        "mood_keywords": ["catchy", "danceable", "tropical", "upbeat", "modern"],
        "description": "Catchy, danceable modern pop with a marimba-style hook and tropical feel.",
        "preview_url": None,
        "melody_contour": [],
    },
    {
        "id": 20,
        "title": "So What",
        "artist": "Miles Davis",
        "year": 1959,
        "genre": ["jazz", "modal"],
        "lyric_snippet": "",
        "mood_keywords": ["cool", "modal", "relaxed", "spacious", "improvised"],
        "description": "Cool, spacious modal jazz built on two chords with a laid-back, exploratory feel.",
        "preview_url": None,
        "melody_contour": [],
    },
]
